package com.rkade;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusListener;
import java.util.List;
import java.util.logging.Logger;

public class ButtonsPanel extends BaseForm implements DeviceListener, ActionListener, FocusListener, ChangeListener {
    private final static Logger logger = Logger.getLogger(ButtonsPanel.class.getName());
    private final List<JButton> switchButtons;
    private final List<JComponent> actionButtons;
    private JPanel mainButtonPanel;
    private JPanel topPanel;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JButton button5;
    private JButton button6;
    private JButton button7;
    private JButton button8;
    private JLabel lblButtons;
    private JPanel actionPanel;
    private JComboBox<String> cbActionBtn6;
    private JLabel lblActionBtn6;
    private JComboBox<String> cbActionBtn7;
    private JLabel lblActionBtn7;
    private JComboBox<String> cbActionBtn8;
    private JLabel lblActionBtn8;
    private JComboBox<String> cbActionBtn9;
    private JLabel lblActionBtn9;
    private Device device = null;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public ButtonsPanel() {
        controls = List.of(lblButtons, actionPanel, lblActionBtn6, lblActionBtn7, lblActionBtn8, lblActionBtn9,
                cbActionBtn6, cbActionBtn7, cbActionBtn8, cbActionBtn9);
        switchButtons = List.of(button1, button2, button3, button4, button5, button6, button7, button8);
        actionButtons = List.of(cbActionBtn6, cbActionBtn7, cbActionBtn8, lblActionBtn6, lblActionBtn7,
                lblActionBtn8, lblActionBtn9, cbActionBtn9);

        setPanelEnabled(false);
        setupControlListener();

        cbActionBtn6.setModel(new DefaultComboBoxModel<>(ButtonAction.getStringValues()));
        cbActionBtn7.setModel(new DefaultComboBoxModel<>(ButtonAction.getStringValues()));
        cbActionBtn8.setModel(new DefaultComboBoxModel<>(ButtonAction.getStringValues()));
        cbActionBtn9.setModel(new DefaultComboBoxModel<>(ButtonAction.getStringValues()));
    }

    @Override
    public void deviceAttached(Device device) {
    }

    @Override
    public void deviceDetached(Device device) {
    }

    @Override
    public void deviceConnected(Device device) {
        this.device = device;
        setPanelEnabled(true);
    }

    @Override
    public void deviceDisconnected(Device device) {
        this.device = null;
        setPanelEnabled(false);
    }

    @Override
    public void deviceUpdated(Device device, String status, DataReport report) {
        if (report != null) {
            //if (report.getReportType() == Device.DATA_REPORT_ID) {
            if (report instanceof ButtonsDataReport buttonsDataReport) {
                updateControls(buttonsDataReport);
            } else if (report instanceof SettingsDataReport settingsDataReport) {
                updateControls(settingsDataReport);
            }
            //}
        }
    }

    private void updateControls(SettingsDataReport settingsDataReport) {
        if (device != null) {
            setEnabled(actionButtons, true);
            setSelectionIfNeeded(cbActionBtn6, settingsDataReport.getButton6Action().ordinal());
            setSelectionIfNeeded(cbActionBtn7, settingsDataReport.getButton7Action().ordinal());
            setSelectionIfNeeded(cbActionBtn8, settingsDataReport.getButton8Action().ordinal());
            setSelectionIfNeeded(cbActionBtn9, settingsDataReport.getButton9Action().ordinal());
        } else {
            setEnabled(actionButtons, false);
        }
    }

    private boolean getButtonState(ButtonsDataReport buttonsDataReport, int buttonIndex) {
        return ((buttonsDataReport.getButtonsState() & (short) Math.pow(2, buttonIndex)) > 0);
    }

    private void updateControls(ButtonsDataReport buttonsDataReport) {
        for (JButton button : switchButtons) {
            button.setSelected(getButtonState(buttonsDataReport, switchButtons.indexOf(button)));
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        boolean status = handleAction(e);
        if (!status) {
            logger.warning("Action failed for:" + e.getActionCommand());
        }
    }

    private boolean handleAction(ActionEvent e) {
        if (e.getActionCommand().equals(cbActionBtn6.getActionCommand())) {
            return device.setButtonAction((short) 6, (byte) cbActionBtn6.getSelectedIndex());
        } else if (e.getActionCommand().equals(cbActionBtn7.getActionCommand())) {
            return device.setButtonAction((short) 7, (byte) cbActionBtn7.getSelectedIndex());
        } else if (e.getActionCommand().equals(cbActionBtn8.getActionCommand())) {
            return device.setButtonAction((short) 8, (byte) cbActionBtn8.getSelectedIndex());
        } else if (e.getActionCommand().equals(cbActionBtn9.getActionCommand())) {
            return device.setButtonAction((short) 9, (byte) cbActionBtn9.getSelectedIndex());
        }
        return true;
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if (device != null) {
            boolean status = true;
            if (!status) {
                logger.warning("State Changed, failed for:" + e.getSource());
            }
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainButtonPanel = new JPanel();
        mainButtonPanel.setLayout(new BorderLayout(0, 0));
        mainButtonPanel.setAutoscrolls(false);
        mainButtonPanel.setMaximumSize(new Dimension(400, 240));
        mainButtonPanel.setMinimumSize(new Dimension(400, 240));
        mainButtonPanel.setName("mainButtonPanel");
        mainButtonPanel.setPreferredSize(new Dimension(400, 240));
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        topPanel.setAutoscrolls(false);
        topPanel.setMaximumSize(new Dimension(200, 205));
        topPanel.setMinimumSize(new Dimension(100, 205));
        topPanel.setPreferredSize(new Dimension(200, 205));
        mainButtonPanel.add(topPanel, BorderLayout.NORTH);
        button1 = new JButton();
        button1.setAutoscrolls(false);
        button1.setEnabled(false);
        button1.setHorizontalAlignment(0);
        button1.setMinimumSize(new Dimension(50, 50));
        button1.setPreferredSize(new Dimension(50, 50));
        button1.setSelected(false);
        button1.setText("1");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        topPanel.add(button1, gbc);
        button2 = new JButton();
        button2.setAutoscrolls(false);
        button2.setEnabled(false);
        button2.setMinimumSize(new Dimension(50, 50));
        button2.setPreferredSize(new Dimension(50, 50));
        button2.setSelected(false);
        button2.setText("2");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        topPanel.add(button2, gbc);
        button3 = new JButton();
        button3.setAutoscrolls(false);
        button3.setEnabled(false);
        button3.setMinimumSize(new Dimension(50, 50));
        button3.setPreferredSize(new Dimension(50, 50));
        button3.setRolloverEnabled(false);
        button3.setSelected(false);
        button3.setText("3");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        topPanel.add(button3, gbc);
        button4 = new JButton();
        button4.setAutoscrolls(false);
        button4.setEnabled(false);
        button4.setMinimumSize(new Dimension(50, 50));
        button4.setPreferredSize(new Dimension(50, 50));
        button4.setRolloverEnabled(false);
        button4.setSelected(false);
        button4.setText("4");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        topPanel.add(button4, gbc);
        button5 = new JButton();
        button5.setAutoscrolls(false);
        button5.setEnabled(false);
        button5.setMinimumSize(new Dimension(50, 50));
        button5.setPreferredSize(new Dimension(50, 50));
        button5.setRolloverEnabled(false);
        button5.setSelected(false);
        button5.setText("5");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        topPanel.add(button5, gbc);
        button6 = new JButton();
        button6.setAutoscrolls(false);
        button6.setEnabled(false);
        button6.setMinimumSize(new Dimension(50, 50));
        button6.setPreferredSize(new Dimension(50, 50));
        button6.setRolloverEnabled(false);
        button6.setSelected(false);
        button6.setText("6");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        topPanel.add(button6, gbc);
        button7 = new JButton();
        button7.setAutoscrolls(false);
        button7.setEnabled(false);
        button7.setMinimumSize(new Dimension(50, 50));
        button7.setPreferredSize(new Dimension(50, 50));
        button7.setRolloverEnabled(false);
        button7.setSelected(false);
        button7.setText("7");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        topPanel.add(button7, gbc);
        button8 = new JButton();
        button8.setAutoscrolls(false);
        button8.setEnabled(false);
        button8.setMinimumSize(new Dimension(50, 50));
        button8.setPreferredSize(new Dimension(50, 50));
        button8.setRolloverEnabled(false);
        button8.setSelected(false);
        button8.setText("8");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        topPanel.add(button8, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainButtonPanel;
    }
}
